version: '3'
services:

  api:
    build: ./api
    container_name: api
    environment:
      - PORT=3000
    ports:
      - 3000:3000

  front-end:
    build: ./front-end
    container_name: front-end
    ports:
      - 4200:80
    links:
      - api
